### ISSUE TITLE
Support Kinsta, Divio platform as well

### ISSUE THREAD

**Issue by davidjeba** [meeb/django-distill-site#1]
https://kinsta.com/static-site-hosting/
&
https://www.divio.com/django-cms/

I want to build a headless microsite generators for small business like
Salons, Shops even Food Truck vendors

anyone want to join this project?
it has to be open source and hosted.
hosted microsites will have 100s of templates which can be customized to certain level
and it will cost $1/month + 10% commission on the transactions through our standard payment gateway

open source can be deployed by developers and use it as they want
im targeting 1M sites in India

**Comment by meeb** [comment]
django-distill already "supports" those platforms. You would just use their build service like you would with Netlify, Cloudflare pages, etc.

This issue board is more suited for issues with the project itself and feature discussions rather than meta issues or project recruitment.

I'll close this for now but feel free to comment if you have an actual issue deploying a django-distill powered project.
